import type { Locale } from "@/lib/i18n/dictionary";

/** Keys are normalised with `normalizeFieldKey`, so `invoice_number` and `invoiceNumber` share one entry. */
const THAI_FIELD_LABELS: Record<string, string> = {
  // shared
  documenttype: "ประเภทเอกสาร",
  documentform: "แบบฟอร์มเอกสาร",
  documentnumber: "เลขที่เอกสาร",
  date: "วันที่",
  description: "รายละเอียด",
  name: "ชื่อ",
  address: "ที่อยู่",
  province: "จังหวัด",
  discount: "ส่วนลด",
  total: "รวม",
  // utility bills
  provider: "ผู้ให้บริการ",
  customername: "ชื่อลูกค้า",
  customeraddress: "ที่อยู่ลูกค้า",
  customertaxid: "เลขประจำตัวผู้เสียภาษีลูกค้า",
  customerphone: "เบอร์โทรลูกค้า",
  accountnumber: "เลขที่บัญชี",
  invoicenumber: "เลขที่ใบแจ้งหนี้",
  invoicedate: "วันที่ใบแจ้งหนี้",
  tarifftype: "ประเภทอัตราค่าไฟ",
  readingdate: "วันที่จดมิเตอร์",
  lastreading: "เลขมิเตอร์ล่าสุด",
  currentreading: "เลขมิเตอร์ปัจจุบัน",
  previousreading: "เลขมิเตอร์ครั้งก่อน",
  unitsconsumed: "หน่วยที่ใช้",
  consumptioncubicmeter: "ปริมาณน้ำที่ใช้ (ลบ.ม.)",
  energycharge: "ค่าพลังงานไฟฟ้า",
  servicecharge: "ค่าบริการ",
  ftrateperunit: "อัตรา Ft ต่อหน่วย",
  ftcharge: "ค่า Ft",
  waterusagecharge: "ค่าน้ำประปา",
  monthlyservicefee: "ค่าบริการรายเดือน",
  subtotalbeforevat: "ยอดก่อนภาษีมูลค่าเพิ่ม",
  vatamount: "ภาษีมูลค่าเพิ่ม",
  totalcurrentbill: "ยอดรวมที่ต้องชำระ",
  totalamount: "ยอดรวม",
  duedate: "วันครบกำหนดชำระ",
  // receipt
  invoicetype: "ประเภทใบกำกับ",
  invoicebook: "เล่มที่",
  invoiceid: "เลขที่ใบกำกับ",
  purchaseorderid: "เลขที่ใบสั่งซื้อ",
  issuername: "ผู้ออกเอกสาร",
  issueraddress: "ที่อยู่ผู้ออกเอกสาร",
  issuertaxid: "เลขประจำตัวผู้เสียภาษีผู้ออก",
  issuerphone: "เบอร์โทรผู้ออกเอกสาร",
  items: "รายการสินค้า",
  itemno: "ลำดับ",
  itemcode: "รหัสสินค้า",
  itemname: "ชื่อสินค้า",
  itemunit: "จำนวน",
  itemunitcost: "ราคาต่อหน่วย",
  itemtotalcost: "ราคารวม",
  itemdiscount: "ส่วนลดรายการ",
  itemnetamount: "ยอดสุทธิรายการ",
  discountdescription: "รายละเอียดส่วนลด",
  discountpercentage: "ส่วนลด (%)",
  totalamountinwords: "จำนวนเงินตัวอักษร",
  paymentmethod: "วิธีชำระเงิน",
  paymentreference: "เลขอ้างอิงการชำระ",
  totalcost: "ยอดรวมก่อนส่วนลด",
  totalcostafterdiscount: "ยอดหลังส่วนลด",
  vat: "ภาษีมูลค่าเพิ่ม",
  grandtotal: "ยอดรวมสุทธิ",
  // bank statement
  bankname: "ธนาคาร",
  accountholdername: "ชื่อเจ้าของบัญชี",
  accounttype: "ประเภทบัญชี",
  branch: "สาขา",
  periodfrom: "ตั้งแต่วันที่",
  periodto: "ถึงวันที่",
  totalwithdrawalamount: "ยอดถอนรวม",
  totaldepositamount: "ยอดฝากรวม",
  transactions: "รายการเดินบัญชี",
  withdrawal: "ถอน",
  deposit: "ฝาก",
  balance: "ยอดคงเหลือ",
  channel: "ช่องทาง",
  // credit card statement
  statementtype: "ประเภทใบแจ้งยอด",
  statementdate: "วันที่ใบแจ้งยอด",
  closingdate: "วันปิดรอบบัญชี",
  cardnumber: "เลขบัตร",
  cardholdername: "ชื่อผู้ถือบัตร",
  bankaddress: "ที่อยู่ธนาคาร",
  banktaxid: "เลขประจำตัวผู้เสียภาษีธนาคาร",
  bankphone: "เบอร์โทรธนาคาร",
  bankfax: "แฟกซ์ธนาคาร",
  creditlimit: "วงเงิน",
  interestrate: "อัตราดอกเบี้ย",
  paymentbydebitaccountno: "บัญชีตัดชำระ",
  transactiondate: "วันที่ทำรายการ",
  postingdate: "วันที่ลงบัญชี",
  foreignamount: "ยอดเงินต่างประเทศ",
  foreigncurrencycode: "สกุลเงินต่างประเทศ",
  amountthb: "ยอดเงิน (บาท)",
  paymentsadjustmentothers: "การชำระเงิน/ปรับปรุง/อื่นๆ",
  previousbalance: "ยอดยกมา",
  thisperiodbalance: "ยอดรอบนี้",
  newbalancepayment: "ยอดที่ต้องชำระ",
  minimumpaymentdue: "ยอดชำระขั้นต่ำ",
  totalpayments: "ยอดชำระรวม",
  totalinterestcharges: "ดอกเบี้ยรวม",
  reward: "คะแนนสะสม",
  paymentbarcodeno: "บาร์โค้ดชำระเงิน",
  // NCB
  reportnumber: "เลขที่รายงาน",
  referencenumber: "เลขอ้างอิง",
  querydate: "วันที่สืบค้น",
  idcardnumber: "เลขบัตรประชาชน",
  fullname: "ชื่อ-นามสกุล",
  dateofbirth: "วันเกิด",
  totalaccounts: "จำนวนบัญชีทั้งหมด",
  accountsunderdispute: "บัญชีที่อยู่ระหว่างโต้แย้ง",
  accounts: "บัญชีสินเชื่อ",
  lendername: "ผู้ให้สินเชื่อ",
  credittype: "ประเภทสินเชื่อ",
  accountstatus: "สถานะบัญชี",
  outstandingbalance: "ยอดคงค้าง",
  // tax deduction certificate
  booknumber: "เล่มที่",
  taxdeductor: "ผู้หักภาษี ณ ที่จ่าย",
  taxpayer: "ผู้ถูกหักภาษี",
  taxid: "เลขประจำตัวผู้เสียภาษี",
  paymenttypes: "ประเภทเงินได้ที่จ่าย",
  paymentdate: "วันที่จ่าย",
  amount: "จำนวนเงิน",
  withholdingtax: "ภาษีที่หัก",
  totaltax: "ภาษีที่หักรวม",
  socialsecurity: "ประกันสังคม",
  year: "ปี",
  taxpayermethod: "วิธีการชำระภาษี",
  // vehicle registration
  registrationdate: "วันที่จดทะเบียน",
  licenseplate: "ทะเบียนรถ",
  vehicletype: "ประเภทรถ",
  brand: "ยี่ห้อ",
  model: "รุ่น",
  color: "สี",
  bodynumber: "เลขตัวถัง",
  enginenumber: "เลขเครื่องยนต์",
  fueltype: "เชื้อเพลิง",
  seatingcapacity: "จำนวนที่นั่ง",
  ownername: "ชื่อเจ้าของ",
  ownerid: "เลขประจำตัวเจ้าของ",
  owneraddress: "ที่อยู่เจ้าของ",
  occupantname: "ชื่อผู้ครอบครอง",
  occupantid: "เลขประจำตัวผู้ครอบครอง",
  // company certificate
  formcode: "รหัสแบบฟอร์ม",
  department: "หน่วยงาน",
  companyname: "ชื่อบริษัท",
  registrationnumber: "เลขทะเบียนนิติบุคคล",
  issuedate: "วันที่ออกเอกสาร",
  legalstatus: "สถานะนิติบุคคล",
  registrationoffice: "สำนักงานทะเบียน",
  registrarname: "นายทะเบียน",
  // civil registration
  header: "หัวเอกสาร",
  nationalidnumber: "เลขประจำตัวประชาชน",
  houseregistrationnumber: "เลขรหัสประจำบ้าน",
  gender: "เพศ",
  nationality: "สัญชาติ",
  age: "อายุ",
  residentialstatus: "สถานภาพที่อยู่อาศัย",
  mothersname: "ชื่อมารดา",
  mothersnationality: "สัญชาติมารดา",
  fathersname: "ชื่อบิดา",
  fathersnationality: "สัญชาติบิดา",
  moveindate: "วันที่ย้ายเข้า",
  additionalnotes: "หมายเหตุเพิ่มเติม",
  remarks: "หมายเหตุ",
  lastupdated: "ปรับปรุงล่าสุด",
  footer: "ท้ายเอกสาร",
  text: "ข้อความ",
  registrar: "นายทะเบียน",
  // CV
  personalinformation: "ข้อมูลส่วนตัว",
  phonenumbers: "เบอร์โทรศัพท์",
  email: "อีเมล",
  religion: "ศาสนา",
  education: "การศึกษา",
  school: "สถานศึกษา",
  level: "ระดับการศึกษา",
  workexperience: "ประสบการณ์ทำงาน",
  title: "ตำแหน่ง",
  company: "บริษัท",
  startdate: "วันที่เริ่ม",
  enddate: "วันที่สิ้นสุด",
  roles: "หน้าที่ความรับผิดชอบ",
  skillsandqualifications: "ทักษะและคุณสมบัติ",
  languages: "ภาษา",
  computerskills: "ทักษะคอมพิวเตอร์",
  communicationskills: "ทักษะการสื่อสาร",
  possibleskillandqualificationsbyai: "ทักษะที่ AI คาดว่ามี",
  additionalinformation: "ข้อมูลเพิ่มเติม",
  evaluation: "ผลประเมิน",
  scores: "คะแนน",
  overall: "ภาพรวม",
  personalinfo: "ข้อมูลส่วนตัว",
  skills: "ทักษะ",
  score: "คะแนน",
  feedback: "ข้อเสนอแนะ",
  experiencelevel: "ระดับประสบการณ์",
  totalyearsofexperience: "ประสบการณ์รวม (ปี)",
  atscompatibility: "ความเข้ากันได้กับระบบ ATS",
  issues: "ปัญหาที่พบ",
  suggestions: "ข้อแนะนำ",
  strengths: "จุดแข็ง",
  weaknesses: "จุดอ่อน",
  missingsections: "หัวข้อที่ขาด",
  improvements: "สิ่งที่ควรปรับปรุง",
  priority: "ลำดับความสำคัญ",
  section: "หัวข้อ",
  issue: "ปัญหา",
  suggestion: "ข้อแนะนำ",
  example: "ตัวอย่าง",
  suggestedkeywords: "คำสำคัญที่แนะนำ",
  industryfitsuggestions: "สายงานที่เหมาะสม",
  executivesummary: "สรุปสำหรับผู้บริหาร",
  // job description
  jobtitle: "ตำแหน่งงาน",
  location: "สถานที่ทำงาน",
  salaryrange: "ช่วงเงินเดือน",
  responsibilities: "หน้าที่ความรับผิดชอบ",
  qualifications: "คุณสมบัติ",
  message: "สถานะ",
};

export function normalizeFieldKey(key: string): string {
  return key.replace(/[^A-Za-z0-9]/g, "").toLowerCase();
}

/** `total_current_bill` / `totalCurrentBill` -> `Total Current Bill`. */
export function humanizeFieldKey(key: string): string {
  const spaced = key
    .replace(/[_-]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .trim();
  return spaced.replace(/\b([a-z])/g, (letter) => letter.toUpperCase());
}

export function fieldLabel(key: string, locale: Locale): string {
  if (locale === "th") {
    const label = THAI_FIELD_LABELS[normalizeFieldKey(key)];
    if (label) return label;
  }
  return humanizeFieldKey(key);
}
